apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: my-project2
  namespace: argocd
spec:
  destinations:
    - namespace: voting-app
      server: https://kubernetes.default.svc
  sourceRepos:
    - '*'
  roles:
    - description: project admin
      name: admin
      policies:
      - p, proj:my-project2:admin, applications, *, my-project2/*, allow
      - p, proj:my-project2:admin, repositories, *, my-project2/*, allow
      - p, proj:my-project2:admin, clusters, *, my-project2/*, allow
      groups:
      - argocd-project2-admin